<?php

return [
    'financials' => [
        'currencies' => [
            ['value' => 'AFA', 'label' => 'Afghan Afghani (؋)'],
            ['value' => 'ALL', 'label' => 'Albanian Lek (Lek)'],
            ['value' => 'DZD', 'label' => 'Algerian Dinar (دج)'],
            ['value' => 'AOA', 'label' => 'Angolan Kwanza (Kz)'],
            ['value' => 'ARS', 'label' => 'Argentine Peso ($)'],
            ['value' => 'AMD', 'label' => 'Armenian Dram (֏)'],
            ['value' => 'AWG', 'label' => 'Aruban Florin (ƒ)'],
            ['value' => 'AUD', 'label' => 'Australian Dollar ($)'],
            ['value' => 'AZN', 'label' => 'Azerbaijani Manat (m)'],
            ['value' => 'BSD', 'label' => 'Bahamian Dollar (B$)'],
            ['value' => 'BHD', 'label' => 'Bahraini Dinar (.د.ب)'],
            ['value' => 'BDT', 'label' => 'Bangladeshi Taka (৳)'],
            ['value' => 'BBD', 'label' => 'Barbadian Dollar (Bds$)'],
            ['value' => 'BYR', 'label' => 'Belarusian Ruble (Br)'],
            ['value' => 'BEF', 'label' => 'Belgian Franc (fr)'],
            ['value' => 'BZD', 'label' => 'Belize Dollar ($)'],
            ['value' => 'BMD', 'label' => 'Bermudan Dollar ($)'],
            ['value' => 'BTN', 'label' => 'Bhutanese Ngultrum (Nu.)'],
            ['value' => 'BTC', 'label' => 'Bitcoin (฿)'],
            ['value' => 'BOB', 'label' => 'Bolivian Boliviano (Bs.)'],
            ['value' => 'BAM', 'label' => 'Bosnia (KM)'],
            ['value' => 'BWP', 'label' => 'Botswanan Pula (P)'],
            ['value' => 'BRL', 'label' => 'Brazilian Real (R$)'],
            ['value' => 'GBP', 'label' => 'British Pound Sterling (£)'],
            ['value' => 'BND', 'label' => 'Brunei Dollar (B$)'],
            ['value' => 'BGN', 'label' => 'Bulgarian Lev (Лв.)'],
            ['value' => 'BIF', 'label' => 'Burundian Franc (FBu)'],
            ['value' => 'KHR', 'label' => 'Cambodian Riel (KHR)'],
            ['value' => 'CAD', 'label' => 'Canadian Dollar ($)'],
            ['value' => 'CVE', 'label' => 'Cape Verdean Escudo ($)'],
            ['value' => 'KYD', 'label' => 'Cayman Islands Dollar ($)'],
            ['value' => 'XOF', 'label' => 'CFA Franc BCEAO (CFA)'],
            ['value' => 'XAF', 'label' => 'CFA Franc BEAC (FCFA)'],
            ['value' => 'XPF', 'label' => 'CFP Franc (₣)'],
            ['value' => 'CLP', 'label' => 'Chilean Peso ($)'],
            ['value' => 'CNY', 'label' => 'Chinese Yuan (¥)'],
            ['value' => 'COP', 'label' => 'Colombian Peso ($)'],
            ['value' => 'KMF', 'label' => 'Comorian Franc (CF)'],
            ['value' => 'CDF', 'label' => 'Congolese Franc (FC)'],
            ['value' => 'CRC', 'label' => 'Costa Rican ColÃ³n (₡)'],
            ['value' => 'HRK', 'label' => 'Croatian Kuna (kn)'],
            ['value' => 'CUC', 'label' => 'Cuban Convertible Peso ($, CUC)'],
            ['value' => 'CZK', 'label' => 'Czech Republic Koruna (Kč)'],
            ['value' => 'DKK', 'label' => 'Danish Krone (Kr.)'],
            ['value' => 'DJF', 'label' => 'Djiboutian Franc (Fdj)'],
            ['value' => 'DOP', 'label' => 'Dominican Peso ($)'],
            ['value' => 'XCD', 'label' => 'East Caribbean Dollar ($)'],
            ['value' => 'EGP', 'label' => 'Egyptian Pound (ج.م)'],
            ['value' => 'ERN', 'label' => 'Eritrean Nakfa (Nfk)'],
            ['value' => 'EEK', 'label' => 'Estonian Kroon (kr)'],
            ['value' => 'ETB', 'label' => 'Ethiopian Birr (Nkf)'],
            ['value' => 'EUR', 'label' => 'Euro (€)'],
            ['value' => 'FKP', 'label' => 'Falkland Islands Pound (£)'],
            ['value' => 'FJD', 'label' => 'Fijian Dollar (FJ$)'],
            ['value' => 'GMD', 'label' => 'Gambian Dalasi (D)'],
            ['value' => 'GEL', 'label' => 'Georgian Lari (ლ)'],
            ['value' => 'DEM', 'label' => 'German Mark (DM)'],
            ['value' => 'GHS', 'label' => 'Ghanaian Cedi (GH₵)'],
            ['value' => 'GIP', 'label' => 'Gibraltar Pound (£)'],
            ['value' => 'GRD', 'label' => 'Greek Drachma (₯, Δρχ, Δρ)'],
            ['value' => 'GTQ', 'label' => 'Guatemalan Quetzal (Q)'],
            ['value' => 'GNF', 'label' => 'Guinean Franc (FG)'],
            ['value' => 'GYD', 'label' => 'Guyanaese Dollar ($)'],
            ['value' => 'HTG', 'label' => 'Haitian Gourde (G)'],
            ['value' => 'HNL', 'label' => 'Honduran Lempira (L)'],
            ['value' => 'HKD', 'label' => 'Hong Kong Dollar ($)'],
            ['value' => 'HUF', 'label' => 'Hungarian Forint (Ft)'],
            ['value' => 'ISK', 'label' => 'Icelandic KrÃ³na (kr)'],
            ['value' => 'INR', 'label' => 'Indian Rupee (₹)'],
            ['value' => 'IDR', 'label' => 'Indonesian Rupiah (Rp)'],
            ['value' => 'IRR', 'label' => 'Iranian Rial (﷼)'],
            ['value' => 'IQD', 'label' => 'Iraqi Dinar (د.ع)'],
            ['value' => 'ILS', 'label' => 'Israeli New Sheqel (₪)'],
            ['value' => 'ITL', 'label' => 'Italian Lira (L,£)'],
            ['value' => 'JMD', 'label' => 'Jamaican Dollar (J$)'],
            ['value' => 'JPY', 'label' => 'Japanese Yen (¥)'],
            ['value' => 'JOD', 'label' => 'Jordanian Dinar (ا.د)'],
            ['value' => 'KZT', 'label' => 'Kazakhstani Tenge (лв)'],
            ['value' => 'KES', 'label' => 'Kenyan Shilling (KSh)'],
            ['value' => 'KWD', 'label' => 'Kuwaiti Dinar (ك.د)'],
            ['value' => 'KGS', 'label' => 'Kyrgystani Som (лв)'],
            ['value' => 'LAK', 'label' => 'Laotian Kip (₭)'],
            ['value' => 'LVL', 'label' => 'Latvian Lats (Ls)'],
            ['value' => 'LBP', 'label' => 'Lebanese Pound (£)'],
            ['value' => 'LSL', 'label' => 'Lesotho Loti (L)'],
            ['value' => 'LRD', 'label' => 'Liberian Dollar ($)'],
            ['value' => 'LYD', 'label' => 'Libyan Dinar (د.ل)'],
            ['value' => 'LTL', 'label' => 'Lithuanian Litas (Lt)'],
            ['value' => 'MOP', 'label' => 'Macanese Pataca ($)'],
            ['value' => 'MKD', 'label' => 'Macedonian Denar (ден)'],
            ['value' => 'MGA', 'label' => 'Malagasy Ariary (Ar)'],
            ['value' => 'MWK', 'label' => 'Malawian Kwacha (MK)'],
            ['value' => 'MYR', 'label' => 'Malaysian Ringgit (RM)'],
            ['value' => 'MVR', 'label' => 'Maldivian Rufiyaa (Rf)'],
            ['value' => 'MRO', 'label' => 'Mauritanian Ouguiya (MRU)'],
            ['value' => 'MUR', 'label' => 'Mauritian Rupee (₨)'],
            ['value' => 'MXN', 'label' => 'Mexican Peso ($)'],
            ['value' => 'MDL', 'label' => 'Moldovan Leu (L)'],
            ['value' => 'MNT', 'label' => 'Mongolian Tugrik (₮)'],
            ['value' => 'MAD', 'label' => 'Moroccan Dirham (MAD)'],
            ['value' => 'MZM', 'label' => 'Mozambican Metical (MT)'],
            ['value' => 'MMK', 'label' => 'Myanmar Kyat (K)'],
            ['value' => 'NAD', 'label' => 'Namibian Dollar ($)'],
            ['value' => 'NPR', 'label' => 'Nepalese Rupee (₨)'],
            ['value' => 'ANG', 'label' => 'Netherlands Antillean Guilder (ƒ)'],
            ['value' => 'TWD', 'label' => 'New Taiwan Dollar ($)'],
            ['value' => 'NZD', 'label' => 'New Zealand Dollar ($)'],
            ['value' => 'NIO', 'label' => 'Nicaraguan CÃ³rdoba (C$)'],
            ['value' => 'NGN', 'label' => 'Nigerian Naira (₦)'],
            ['value' => 'KPW', 'label' => 'North Korean Won (₩)'],
            ['value' => 'NOK', 'label' => 'Norwegian Krone (kr)'],
            ['value' => 'OMR', 'label' => 'Omani Rial (.ع.ر)'],
            ['value' => 'PKR', 'label' => 'Pakistani Rupee (₨)'],
            ['value' => 'PAB', 'label' => 'Panamanian Balboa (B/.)'],
            ['value' => 'PGK', 'label' => 'Papua New Guinean Kina (K)'],
            ['value' => 'PYG', 'label' => 'Paraguayan Guarani (₲)'],
            ['value' => 'PEN', 'label' => 'Peruvian Nuevo Sol (S/.)'],
            ['value' => 'PHP', 'label' => 'Philippine Peso (₱)'],
            ['value' => 'PLN', 'label' => 'Polish Zloty (zł)'],
            ['value' => 'QAR', 'label' => 'Qatari Rial (ق.ر)'],
            ['value' => 'RON', 'label' => 'Romanian Leu (lei)'],
            ['value' => 'RUB', 'label' => 'Russian Ruble (₽)'],
            ['value' => 'RWF', 'label' => 'Rwandan Franc (FRw)'],
            ['value' => 'SVC', 'label' => 'Salvadoran ColÃ³n (₡)'],
            ['value' => 'WST', 'label' => 'Samoan Tala (SAT)'],
            ['value' => 'SAR', 'label' => 'Saudi Riyal (﷼)'],
            ['value' => 'RSD', 'label' => 'Serbian Dinar (din)'],
            ['value' => 'SCR', 'label' => 'Seychellois Rupee (SRe)'],
            ['value' => 'SLL', 'label' => 'Sierra Leonean Leone (Le)'],
            ['value' => 'SGD', 'label' => 'Singapore Dollar ($)'],
            ['value' => 'SKK', 'label' => 'Slovak Koruna (Sk)'],
            ['value' => 'SBD', 'label' => 'Solomon Islands Dollar (Si$)'],
            ['value' => 'SOS', 'label' => 'Somali Shilling (Sh.so.)'],
            ['value' => 'ZAR', 'label' => 'South African Rand (R)'],
            ['value' => 'KRW', 'label' => 'South Korean Won (₩)'],
            ['value' => 'XDR', 'label' => 'Special Drawing Rights (SDR)'],
            ['value' => 'LKR', 'label' => 'Sri Lankan Rupee (Rs)'],
            ['value' => 'SHP', 'label' => 'St. Helena Pound (£)'],
            ['value' => 'SDG', 'label' => 'Sudanese Pound (.س.ج)'],
            ['value' => 'SRD', 'label' => 'Surinamese Dollar ($)'],
            ['value' => 'SZL', 'label' => 'Swazi Lilangeni (E)'],
            ['value' => 'SEK', 'label' => 'Swedish Krona (kr)'],
            ['value' => 'CHF', 'label' => 'Swiss Franc (CHf)'],
            ['value' => 'SYP', 'label' => 'Syrian Pound (LS)'],
            ['value' => 'STD', 'label' => 'São Tomé and Príncipe Dobra (Db)'],
            ['value' => 'TJS', 'label' => 'Tajikistani Somoni (SM)'],
            ['value' => 'TZS', 'label' => 'Tanzanian Shilling (TSh)'],
            ['value' => 'THB', 'label' => 'Thai Baht (฿)'],
            ['value' => 'TOP', 'label' => 'Tongan paanga ($)'],
            ['value' => 'TTD', 'label' => 'Trinidad & Tobago Dollar ($)'],
            ['value' => 'TND', 'label' => 'Tunisian Dinar (ت.د)'],
            ['value' => 'TRY', 'label' => 'Turkish Lira (₺)'],
            ['value' => 'TMT', 'label' => 'Turkmenistani Manat (T)'],
            ['value' => 'UGX', 'label' => 'Ugandan Shilling (USh)'],
            ['value' => 'UAH', 'label' => 'Ukrainian Hryvnia (₴)'],
            ['value' => 'AED', 'label' => 'United Arab Emirates Dirham (إ.د)'],
            ['value' => 'UYU', 'label' => 'Uruguayan Peso ($)'],
            ['value' => 'USD', 'label' => 'US Dollar ($)'],
            ['value' => 'UZS', 'label' => 'Uzbekistan Som (лв)'],
            ['value' => 'VUV', 'label' => 'Vanuatu Vatu (VT)'],
            ['value' => 'VEF', 'label' => 'Venezuelan BolÃvar (Bs)'],
            ['value' => 'VND', 'label' => 'Vietnamese Dong (₫)'],
            ['value' => 'YER', 'label' => 'Yemeni Rial (﷼)'],
            ['value' => 'ZMK', 'label' => 'Zambian Kwacha (Z)']
        ],
        'gst'        => 7,
        /*
        |--------------------------------------------------------------------------
        | Application Currency
        |--------------------------------------------------------------------------
        |
        | Here you may specify the default currency for your application, which
        | will be used by the Nova Curency Fields functions. We have gone
        | ahead and set this to a sensible default for you out of the box.
        |
        */
        'currency' => 'SGD',
    ],
    'timezone'   => [
        ['label' => '(GMT-11:00) Midway Island', 'value' => 'Pacific/Midway'],
        ['label' => '(GMT-11:00) Samoa', 'value' => 'Pacific/Samoa'],
        ['label' => '(GMT-10:00) Hawaii', 'value' => 'Pacific/Honolulu'],
        ['label' => '(GMT-09:00) Alaska', 'value' => 'US/Alaska'],
        ['label' => '(GMT-08:00) Pacific Time (US &amp; Canada)', 'value' => 'America/Los_Angeles'],
        ['label' => '(GMT-08:00) Tijuana', 'value' => 'America/Tijuana'],
        ['label' => '(GMT-07:00) Arizona', 'value' => 'US/Arizona'],
        ['label' => '(GMT-07:00) Chihuahua', 'value' => 'America/Chihuahua'],
        ['label' => '(GMT-07:00) La Paz', 'value' => 'America/Chihuahua'],
        ['label' => '(GMT-07:00) Mazatlan', 'value' => 'America/Mazatlan'],
        ['label' => '(GMT-07:00) Mountain Time (US &amp; Canada)', 'value' => 'US/Mountain'],
        ['label' => '(GMT-06:00) Central America', 'value' => 'America/Managua'],
        ['label' => '(GMT-06:00) Central Time (US &amp; Canada)', 'value' => 'US/Central'],
        ['label' => '(GMT-06:00) Guadalajara', 'value' => 'America/Mexico_City'],
        ['label' => '(GMT-06:00) Mexico City', 'value' => 'America/Mexico_City'],
        ['label' => '(GMT-06:00) Monterrey', 'value' => 'America/Monterrey'],
        ['label' => '(GMT-06:00) Saskatchewan', 'value' => 'Canada/Saskatchewan'],
        ['label' => '(GMT-05:00) Bogota', 'value' => 'America/Bogota'],
        ['label' => '(GMT-05:00) Eastern Time (US &amp; Canada)', 'value' => 'US/Eastern'],
        ['label' => '(GMT-05:00) Indiana (East)', 'value' => 'US/East-Indiana'],
        ['label' => '(GMT-05:00) Lima', 'value' => 'America/Lima'],
        ['label' => '(GMT-05:00) Quito', 'value' => 'America/Bogota'],
        ['label' => '(GMT-04:00) Atlantic Time (Canada)', 'value' => 'Canada/Atlantic'],
        ['label' => '(GMT-04:30) Caracas', 'value' => 'America/Caracas'],
        ['label' => '(GMT-04:00) La Paz', 'value' => 'America/La_Paz'],
        ['label' => '(GMT-04:00) Santiago', 'value' => 'America/Santiago'],
        ['label' => '(GMT-03:30) Newfoundland', 'value' => 'Canada/Newfoundland'],
        ['label' => '(GMT-03:00) Brasilia', 'value' => 'America/Sao_Paulo'],
        ['label' => '(GMT-03:00) Buenos Aires', 'value' => 'America/Argentina/Buenos_Aires'],
        ['label' => '(GMT-03:00) Georgetown', 'value' => 'America/Argentina/Buenos_Aires'],
        ['label' => '(GMT-03:00) Greenland', 'value' => 'America/Godthab'],
        ['label' => '(GMT-02:00) Mid-Atlantic', 'value' => 'America/Noronha'],
        ['label' => '(GMT-01:00) Azores', 'value' => 'Atlantic/Azores'],
        ['label' => '(GMT-01:00) Cape Verde Is.', 'value' => 'Atlantic/Cape_Verde'],
        ['label' => '(GMT+00:00) Casablanca', 'value' => 'Africa/Casablanca'],
        ['label' => '(GMT+00:00) Edinburgh', 'value' => 'Europe/London'],
        ['label' => '(GMT+00:00) Greenwich Mean Time : Dublin', 'value' => 'Etc/Greenwich'],
        ['label' => '(GMT+00:00) Lisbon', 'value' => 'Europe/Lisbon'],
        ['label' => '(GMT+00:00) London', 'value' => 'Europe/London'],
        ['label' => '(GMT+00:00) Monrovia', 'value' => 'Africa/Monrovia'],
        ['label' => '(GMT+00:00) UTC', 'value' => 'UTC'],
        ['label' => '(GMT+01:00) Amsterdam', 'value' => 'Europe/Amsterdam'],
        ['label' => '(GMT+01:00) Belgrade', 'value' => 'Europe/Belgrade'],
        ['label' => '(GMT+01:00) Berlin', 'value' => 'Europe/Berlin'],
        ['label' => '(GMT+01:00) Bern', 'value' => 'Europe/Berlin'],
        ['label' => '(GMT+01:00) Bratislava', 'value' => 'Europe/Bratislava'],
        ['label' => '(GMT+01:00) Brussels', 'value' => 'Europe/Brussels'],
        ['label' => '(GMT+01:00) Budapest', 'value' => 'Europe/Budapest'],
        ['label' => '(GMT+01:00) Copenhagen', 'value' => 'Europe/Copenhagen'],
        ['label' => '(GMT+01:00) Ljubljana', 'value' => 'Europe/Ljubljana'],
        ['label' => '(GMT+01:00) Madrid', 'value' => 'Europe/Madrid'],
        ['label' => '(GMT+01:00) Paris', 'value' => 'Europe/Paris'],
        ['label' => '(GMT+01:00) Prague', 'value' => 'Europe/Prague'],
        ['label' => '(GMT+01:00) Rome', 'value' => 'Europe/Rome'],
        ['label' => '(GMT+01:00) Sarajevo', 'value' => 'Europe/Sarajevo'],
        ['label' => '(GMT+01:00) Skopje', 'value' => 'Europe/Skopje'],
        ['label' => '(GMT+01:00) Stockholm', 'value' => 'Europe/Stockholm'],
        ['label' => '(GMT+01:00) Vienna', 'value' => 'Europe/Vienna'],
        ['label' => '(GMT+01:00) Warsaw', 'value' => 'Europe/Warsaw'],
        ['label' => '(GMT+01:00) West Central Africa', 'value' => 'Africa/Lagos'],
        ['label' => '(GMT+01:00) Zagreb', 'value' => 'Europe/Zagreb'],
        ['label' => '(GMT+02:00) Athens', 'value' => 'Europe/Athens'],
        ['label' => '(GMT+02:00) Bucharest', 'value' => 'Europe/Bucharest'],
        ['label' => '(GMT+02:00) Cairo', 'value' => 'Africa/Cairo'],
        ['label' => '(GMT+02:00) Harare', 'value' => 'Africa/Harare'],
        ['label' => '(GMT+02:00) Helsinki', 'value' => 'Europe/Helsinki'],
        ['label' => '(GMT+02:00) Istanbul', 'value' => 'Europe/Istanbul'],
        ['label' => '(GMT+02:00) Jerusalem', 'value' => 'Asia/Jerusalem'],
        ['label' => '(GMT+02:00) Kyiv', 'value' => 'Europe/Helsinki'],
        ['label' => '(GMT+02:00) Pretoria', 'value' => 'Africa/Johannesburg'],
        ['label' => '(GMT+02:00) Riga', 'value' => 'Europe/Riga'],
        ['label' => '(GMT+02:00) Sofia', 'value' => 'Europe/Sofia'],
        ['label' => '(GMT+02:00) Tallinn', 'value' => 'Europe/Tallinn'],
        ['label' => '(GMT+02:00) Vilnius', 'value' => 'Europe/Vilnius'],
        ['label' => '(GMT+03:00) Baghdad', 'value' => 'Asia/Baghdad'],
        ['label' => '(GMT+03:00) Kuwait', 'value' => 'Asia/Kuwait'],
        ['label' => '(GMT+03:00) Minsk', 'value' => 'Europe/Minsk'],
        ['label' => '(GMT+03:00) Nairobi', 'value' => 'Africa/Nairobi'],
        ['label' => '(GMT+03:00) Riyadh', 'value' => 'Asia/Riyadh'],
        ['label' => '(GMT+03:00) Volgograd', 'value' => 'Europe/Volgograd'],
        ['label' => '(GMT+03:30) Tehran', 'value' => 'Asia/Tehran'],
        ['label' => '(GMT+04:00) Abu Dhabi', 'value' => 'Asia/Muscat'],
        ['label' => '(GMT+04:00) Baku', 'value' => 'Asia/Baku'],
        ['label' => '(GMT+04:00) Moscow', 'value' => 'Europe/Moscow'],
        ['label' => '(GMT+04:00) Muscat', 'value' => 'Asia/Muscat'],
        ['label' => '(GMT+04:00) St. Petersburg', 'value' => 'Europe/Moscow'],
        ['label' => '(GMT+04:00) Tbilisi', 'value' => 'Asia/Tbilisi'],
        ['label' => '(GMT+04:00) Yerevan', 'value' => 'Asia/Yerevan'],
        ['label' => '(GMT+04:30) Kabul', 'value' => 'Asia/Kabul'],
        ['label' => '(GMT+05:00) Islamabad', 'value' => 'Asia/Karachi'],
        ['label' => '(GMT+05:00) Karachi', 'value' => 'Asia/Karachi'],
        ['label' => '(GMT+05:00) Tashkent', 'value' => 'Asia/Tashkent'],
        ['label' => '(GMT+05:30) Chennai', 'value' => 'Asia/Calcutta'],
        ['label' => '(GMT+05:30) Kolkata', 'value' => 'Asia/Kolkata'],
        ['label' => '(GMT+05:30) Mumbai', 'value' => 'Asia/Calcutta'],
        ['label' => '(GMT+05:30) New Delhi', 'value' => 'Asia/Calcutta'],
        ['label' => '(GMT+05:30) Sri Jayawardenepura', 'value' => 'Asia/Calcutta'],
        ['label' => '(GMT+05:45) Kathmandu', 'value' => 'Asia/Katmandu'],
        ['label' => '(GMT+06:00) Almaty', 'value' => 'Asia/Almaty'],
        ['label' => '(GMT+06:00) Astana', 'value' => 'Asia/Dhaka'],
        ['label' => '(GMT+06:00) Dhaka', 'value' => 'Asia/Dhaka'],
        ['label' => '(GMT+06:00) Ekaterinburg', 'value' => 'Asia/Yekaterinburg'],
        ['label' => '(GMT+06:30) Rangoon', 'value' => 'Asia/Rangoon'],
        ['label' => '(GMT+07:00) Bangkok', 'value' => 'Asia/Bangkok'],
        ['label' => '(GMT+07:00) Hanoi', 'value' => 'Asia/Bangkok'],
        ['label' => '(GMT+07:00) Jakarta', 'value' => 'Asia/Jakarta'],
        ['label' => '(GMT+07:00) Novosibirsk', 'value' => 'Asia/Novosibirsk'],
        ['label' => '(GMT+08:00) Beijing', 'value' => 'Asia/Hong_Kong'],
        ['label' => '(GMT+08:00) Chongqing', 'value' => 'Asia/Chongqing'],
        ['label' => '(GMT+08:00) Hong Kong', 'value' => 'Asia/Hong_Kong'],
        ['label' => '(GMT+08:00) Krasnoyarsk', 'value' => 'Asia/Krasnoyarsk'],
        ['label' => '(GMT+08:00) Kuala Lumpur', 'value' => 'Asia/Kuala_Lumpur'],
        ['label' => '(GMT+08:00) Perth', 'value' => 'Australia/Perth'],
        ['label' => '(GMT+08:00) Singapore', 'value' => 'Asia/Singapore'],
        ['label' => '(GMT+08:00) Taipei', 'value' => 'Asia/Taipei'],
        ['label' => '(GMT+08:00) Ulaan Bataar', 'value' => 'Asia/Ulan_Bator'],
        ['label' => '(GMT+08:00) Urumqi', 'value' => 'Asia/Urumqi'],
        ['label' => '(GMT+09:00) Irkutsk', 'value' => 'Asia/Irkutsk'],
        ['label' => '(GMT+09:00) Osaka', 'value' => 'Asia/Tokyo'],
        ['label' => '(GMT+09:00) Sapporo', 'value' => 'Asia/Tokyo'],
        ['label' => '(GMT+09:00) Seoul', 'value' => 'Asia/Seoul'],
        ['label' => '(GMT+09:00) Tokyo', 'value' => 'Asia/Tokyo'],
        ['label' => '(GMT+09:30) Adelaide', 'value' => 'Australia/Adelaide'],
        ['label' => '(GMT+09:30) Darwin', 'value' => 'Australia/Darwin'],
        ['label' => '(GMT+10:00) Brisbane', 'value' => 'Australia/Brisbane'],
        ['label' => '(GMT+10:00) Canberra', 'value' => 'Australia/Canberra'],
        ['label' => '(GMT+10:00) Guam', 'value' => 'Pacific/Guam'],
        ['label' => '(GMT+10:00) Hobart', 'value' => 'Australia/Hobart'],
        ['label' => '(GMT+10:00) Melbourne', 'value' => 'Australia/Melbourne'],
        ['label' => '(GMT+10:00) Port Moresby', 'value' => 'Pacific/Port_Moresby'],
        ['label' => '(GMT+10:00) Sydney', 'value' => 'Australia/Sydney'],
        ['label' => '(GMT+10:00) Yakutsk', 'value' => 'Asia/Yakutsk'],
        ['label' => '(GMT+11:00) Vladivostok', 'value' => 'Asia/Vladivostok'],
        ['label' => '(GMT+12:00) Auckland', 'value' => 'Pacific/Auckland'],
        ['label' => '(GMT+12:00) Fiji', 'value' => 'Pacific/Fiji'],
        ['label' => '(GMT+12:00) International Date Line West', 'value' => 'Pacific/Kwajalein'],
        ['label' => '(GMT+12:00) Kamchatka', 'value' => 'Asia/Kamchatka'],
        ['label' => '(GMT+12:00) Magadan', 'value' => 'Asia/Magadan'],
        ['label' => '(GMT+12:00) Marshall Is.', 'value' => 'Pacific/Fiji'],
        ['label' => '(GMT+12:00) New Caledonia', 'value' => 'Asia/Magadan'],
        ['label' => '(GMT+12:00) Solomon Is.', 'value' => 'Asia/Magadan'],
        ['label' => '(GMT+12:00) Wellington', 'value' => 'Pacific/Auckland'],
        ['label' => '(GMT+13:00) Nuku\'alofa', 'value' => 'Pacific/Tongatapu']
    ]
];
